version: "3.8"

services:
    dev:
        container_name: web-summer-camp-dev
        build: ./.docker/dev
        ports:
            - "127.0.0.1:8000:8000" # Local PHP server
        volumes:
            - .:/app